server:
  port: 8084
spring:
  application:
    name: powerserver   #权限的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8088/eureka/
