server:
  port: 8086
spring:
  application:
    name: voucherserver   #凭证的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8088/eureka/